name = "ana-leticia-gram-energia"
main = "cloudflare-worker.ts"
compatibility_date = "2026-08-17"

[assets]
directory = "./cloudflare-dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

